files:
  - source: /**/src/main/resources/fi/post/daas/registers/enrichment/web/
    translation: >-
      /**/src/main/resources/fi/post/daas/registers/enrichment/web/Crowdin/%two_letters_code%.%original_file_name%
